version: "3"
services:
  app:
    container_name: app
    restart: always  
    build: .
    ports:
      - "8080:8080"
    links:
      - elemongo
    environment: 
      - ELEMENTOR_DB_HOST_PORT='elemongo:27017/test'
      - ELEMENTOR_WEB_PORT=8080  
  elemongo:
    container_name: elemongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"